services:
  opa:
    image: docker.io/openpolicyagent/opa:0.34.2-rootless
    ports:
      - "8181:8181"
    command:
      - "run"
      - "--server"
      - "--config-file=/config/opa-conf.yaml"
    volumes:
      - "./opa:/config"
  zookeeper:
    image: confluentinc/cp-zookeeper:6.2.1
    ports:
      - "2181:2181"
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
      - ZOOKEEPER_CLIENT_PORT=2181
  broker:
    image: confluentinc/cp-kafka:6.2.1
    ports:
      - "9092:9092"
    environment:
      CLASSPATH: "/plugin/*"
      KAFKA_AUTHORIZER_CLASS_NAME: com.bisnode.kafka.authorization.OpaAuthorizer
      KAFKA_OPA_AUTHORIZER_URL: http://opa:8181/v1/data/kafka/authz/allow
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
    volumes:
      - "./plugin:/plugin"
      - "./cert:/etc/kafka/secrets"
    depends_on:
      - opa
      - zookeeper
