---
version: '3.5'
services:
  opa:
    image: docker.io/openpolicyagent/opa:0.34.2-rootless
    ports:
      - "8181:8181"
    command:
      - "run"
      - "--server"
      - "--config-file=/config/opa-conf.yaml"
    volumes:
      - "./opa:/config"
  zookeeper:
    image: confluentinc/cp-zookeeper:6.2.1
    ports:
      - "2181:2181"
    environment:
      ALLOW_ANONYMOUS_LOGIN: yes
      ZOOKEEPER_CLIENT_PORT: 2181
      # SASL_SSL config
      KAFKA_OPTS: -Djava.security.auth.login.config=/etc/kafka/secrets/zookeeper_jaas.conf
                  -Dzookeeper.authProvider.1=org.apache.zookeeper.server.auth.SASLAuthenticationProvider
                  -DrequireClientAuthScheme=sasl
                  -Dzookeeper.allowSaslFailedClients=true
    volumes:
      - ./zookeeper_jaas.conf:/etc/kafka/secrets/zookeeper_jaas.conf
  broker:
    image: confluentinc/cp-kafka:6.2.1
    hostname: broker
    container_name: broker
    ports:
      - "9093:9093"
      - "9094:9094"
    environment:
      CLASSPATH: "/plugin/*"
      KAFKA_AUTHORIZER_CLASS_NAME: com.bisnode.kafka.authorization.OpaAuthorizer
      KAFKA_OPA_AUTHORIZER_URL: http://opa:8181/v1/data/kafka/authz/allow
      KAFKA_OPA_AUTHORIZER_CACHE_EXPIRE_AFTER_SECONDS: 10 # For development only
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: "zookeeper:2181"
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"
      KAFKA_SSL_KEYSTORE_FILENAME: server.keystore
      KAFKA_SSL_KEYSTORE_CREDENTIALS: credentials.txt
      KAFKA_SSL_KEY_CREDENTIALS: credentials.txt
      KAFKA_SSL_TRUSTSTORE_FILENAME: server.truststore
      KAFKA_SSL_TRUSTSTORE_CREDENTIALS: credentials.txt
      KAFKA_SSL_CLIENT_AUTH: required
      # SSL only config
#      KAFKA_INTER_BROKER_LISTENER_NAME: SSL
#      KAFKA_ADVERTISED_LISTENERS: SSL://localhost:9093
#      KAFKA_LISTENERS: SSL://:9093
      # SASL_SSL and ssl
      KAFKA_INTER_BROKER_LISTENER_NAME: SASL_SSL
      KAFKA_LISTENERS: SSL://:9093,SASL_SSL://:9094
      KAFKA_ADVERTISED_LISTENERS: SSL://localhost:9093,SASL_SSL://localhost:9094
      KAFKA_SASL_ENABLED_MECHANISMS: PLAIN
      KAFKA_SASL_MECHANISM_INTER_BROKER_PROTOCOL: PLAIN
      KAFKA_OPTS: -Djava.security.auth.login.config=/etc/kafka/kafka_server_jaas.conf
    volumes:
      - "./plugin:/plugin"
      - "./cert/server:/etc/kafka/secrets"
      - "./kafka_server_jaas.conf:/etc/kafka/kafka_server_jaas.conf"
    depends_on:
      - opa
      - zookeeper
